---
title: "Work package 4.  Governance, Community Building & Training"
format: html
css: styles.css
output: html_document
---

## 🎯 Objectivs

This work package will develop a strategy to sustain and show the advantages of adapting the Bio-TAPERSTY in OMICS. This will involve training ambassadors, 
creating accessible educational materials, organizing workshops and conferences, and obtaining annual reports about how Bio-TAPESTRY helps in reducing energy 
consumption and CO2 footprint.

## 🚧 Tasks



### Task 4.1 - Train and operationalise the Bio-TAPERSTY ambassadors.

**4.1.a** -- Define ambassador role, core responsibilities and success indicators.   
**4.1.b** -- Develop a concise ambassador training curriculum and materials.   
**4.1.c** -- Deliver structured training sessions (remote + recorded) for partners nominated as ambassadors.   
**4.1.d** -- Provide a lightweight toolkit for ambassadors (reporting template, FAQ, escalation path).   
**4.1.e** -- Establish a reporting cadence and short activity log format for ambassador contributions.   


### Task 4.2 - Develop and release open-source training kits for omics researchers.

**4.2.a** -- Define learning objectives on applying the recommender and repurposer to generate DPOs from omics data.   
**4.2.b** -- Develop modular training materials with domain-specific examples and hands-on exercises.   
**4.2.c** -- Pilot the kits with omics researchers, refine based on feedback, and publish as openly available resources (e.g. Galaxy Training Network, Tess, Zenodo).   



### Task 4.3 - Produce annual adaptation report from partner feedback on Bio-TAPESTRY.

**4.3.a** -- Design and deploy a targeted survey to testing partners/researchers after practical use of Bio-TAPESTRY.   
**4.3.b** -- Analyse responses to identify strengths, gaps, and improvement priorities.   
**4.3.c** -- Compile findings into an adaptation report with actionable recommendations and circulate to work pakages leaders.   

## 🚚 Deliverables:

* **D4.1** -- Bio-TAPERSTY ambassadors Training 
* **D4.2** -- Open-source training kits enabling omics researchers to maximise the value of their data with Bio-TAPERSTY
* **D4.3** -- Adaptation report based on partners survey feedback following the use of Bio-TAPERSTY.